### ISSUE TITLE
Add roll-over to get numbers

### ISSUE THREAD

**Issue by rambaut** [artic-network/rampart#14]
Roll over graphs to show actual numbers in popup box.

**Comment by jameshadfield** [comment]
Done 🎉 

<img width="226" alt="image" src="https://user-images.githubusercontent.com/8350992/57451850-1418df00-7282-11e9-85ed-b560c3e34a16.png">
<img width="223" alt="image" src="https://user-images.githubusercontent.com/8350992/57451870-1aa75680-7282-11e9-92ef-00db767adfd9.png">
