### ISSUE TITLE
Create sample setup front end.

### ISSUE THREAD

**Issue by rambaut** [artic-network/rampart#25]
This would probably be a separate app from RAMPART as it would be run at sample receipt before the lab work begins. Would allow you to provide sample IDs, select intended protocols, assign barcodes, specify which RAMPART instance to use (i.e., what virus it is) etc. 

Ultimately it should provide a customized protocol ready for lamination (you did bring the laminator didn't you @igoodfel?).

**Comment by jameshadfield** [comment]
I implemented this in RAMPART as it seemed the most pragmatic, but we can create a second sample-management app with laminator interface if needed!

* For choosing the mapping reference i've added a drop-down to choose from ARTIC protocols, currently just two JSONs in the repo, but we should add more of these. Possible add standardised reference panels (FASTAs) too.

* It allows you to change the names associated with barcodes as often as you like, and if there are multiple barcodes with the same name they get collapsed into a single sample.

**Comment by rambaut** [comment]
This is good for now but ultimately this needs to be persistent. I suspect we need a local database to store this information and have a UI for setting things up.
