### ISSUE TITLE
Visualise genetic distance from reference

### ISSUE THREAD

**Issue by rambaut** [artic-network/rampart#32]
The call to MiniMap2 in map_single_fastq.py returns the %similarity to the mapped reference. It would be good to be able to include this as a chart in each sample panel (either for the majority mapping or selecting a specific reference).

**Comment by jameshadfield** [comment]
I wonder if we should just call the SNPs and draw a quick tree with the reference panel + samples?

**Comment by rambaut** [comment]
I don't think so. It would add new layers of complexity. Ultimately, when we make RAMPART more modular, then this sort of thing could be added but at the moment I think we should focus on it being a  tool for diagnosing sequencing issues and looking at performance.

**Comment by rambaut** [comment]
It would just be useful to know how close the reads are to to their best mapping reference (this information is being returned by the mapping script).

**Comment by jameshadfield** [comment]
Prototype now implemented in 53aa9acf911af565c488ed308f8484e24bf8ad6b

![image](https://user-images.githubusercontent.com/8350992/72122614-5a9b7c00-33c3-11ea-8f6e-3f1096498dbd.png)

The panel placement hasn't been given much thought & the presence of `unmapped` having similarity values is somewhat worrying 🤦‍♂

**Comment by jameshadfield** [comment]
The `unmapped` 🐛 is fixed -- it was caused by ambiguous mapping results being labeled as `unmapped`. We no longer store similarities for these reads.

![image](https://user-images.githubusercontent.com/8350992/72123133-2fb22780-33c5-11ea-8f08-f40975e86189.png)
