### ISSUE TITLE
Dynamically pick colour range for different samples

### ISSUE THREAD

**Issue by rambaut** [artic-network/rampart#33]
Currently, at line 77 in processServerData.js, `state.sampleColours = createSampleColours(25);` creates an array of 25 colours on a spectrum. This allows for the 24 native barcodes + 1 extra (i.e., 'none'). This needs to be dynamic for the number of samples. 

If the number samples is greater than this then there is an array out of bounds exception thrown in some of the components that use it. These should probably 'wrap' around to avoid the exception.

**Comment by rambaut** [comment]
Also with 25 colour spectrum, the adjacent ones are very similar. Should probably spread more when using fewer samples. Also allowing some customization would be good - i.e., colour 'groups' for related samples, greys for controls etc.

**Comment by jameshadfield** [comment]
Implemented in 5cd9929779a0c7202786befe7614617475d04868
* The default colours (`src/utils/colours.js`) still aren't perfect, but they try to be more spaced apart.
* No limit on the number of samples
* You can manually change sample (and reference) colours via a new UI in the "settings" sidebar
