### ISSUE TITLE
Dynamic inclusion of references in the reference heatmap chart

### ISSUE THREAD

**Issue by rambaut** [artic-network/rampart#35]
We will often have many more reference genomes than there is space on the reference heatmap but only a few of them will have any significant number of reads mapping to them. This chart should dynamically adjust to only show top references. Perhaps specify a maximum  number plus some cutoff for the minimum number of reads for it to be shown.

**Comment by jameshadfield** [comment]
Closed in f7488a02c57feb5faeb9d000d11ccddb1d8b5c42
