### ISSUE TITLE
RAMPART & MinKNOW Barcoding

### ISSUE THREAD

**Issue by mattdmem** [artic-network/rampart#63]
We are about to start our 1st nCov run using the ARTIC protocol. We plan to use RAMPART to monitor the run. Do we need to have barcoding on or off in MinKNOW? If we have it on the fastq_pass folder will have sub folders for barcode01 barcode02 etc - will that still work with RAMPART?

I put this in the nCov repo too as we need to know pretty quickly. I think we will probably default to no barcoding if we don't hear back!

Thanks!

**Comment by rambaut** [comment]
At the moment RAMPART requires MinKNOW barcoding to be off - it can only watch one fastq folder and will do its own demuxing. We will be offering MinKNOW barcoding support soon.

**Comment by mattdmem** [comment]
Thanks! We'll turn it off then.
