### ISSUE TITLE
Support for fastq.gz

### ISSUE THREAD

**Issue by mattdmem** [artic-network/rampart#64]
We had an issue where MinKNOW was automatically creating fastq.gz files instead of uncompressed fastqs. I know that rampart can't handle this but maybe it can be supported in the futue?

**Comment by jameshadfield** [comment]
> MinKNOW was automatically creating fastq.gz

Did not know if could do this 😦

**Comment by mattdmem** [comment]
It's new - that and a different fast5 compression - I think they are off by default, but we tried to start our run twice because we were getting fastq.gz and we checked that setting in the interface. This was the latest GridION release - I don't know if it's in the MinKNOW for MinIONs yet. 

I just resorted to a loop that was watching for fastq.gz and decompressing so that rampart could see them.
