### ISSUE TITLE
No data showing when using remote browser

### ISSUE THREAD

**Issue by Psy-Fer** [artic-network/rampart#65]
Hello,

Great stuff! Really great work.

I'm trying to get set up so I can monitor RAMPART from home. I'm on our VPN, and i've forward ports 3000 and 3001 through our port NAT switch. 

When I run the RAMPART example
```
rampart --protocol ../../example_protocols/EBOV --clearAnnotated
```

I can then go to `<IP of P-NAT>:3000` and I get  the following

![image](https://user-images.githubusercontent.com/8985577/76924798-9440b400-692b-11ea-9dbe-f629a553201f.png)

It does not update or refresh.

I did an X11 session, and opened up firefox, did a local load on the system, and it seems to be working fine.

Am I doing something wrong?

Cheers.
James

**Comment by rambaut** [comment]
It also uses port 3001 to communicate so you will need to forward that as well. You can change the ports it uses using, i.e.,  `--ports 4000 4001`.

**Comment by rambaut** [comment]
If you run rampart with `--verbose`, do you see a message about client connecting when you reload the browser on the remote machine?

**Comment by jameshadfield** [comment]
Quick update as James & I chatted over twitter & the connection to port 3001 (where we transmit data) was being blocked in the browser. This could be because we use sockets on that port. @Psy-Fer please comment here if you find a fix!

**Comment by Psy-Fer** [comment]
Turns out I was being too security minded and when I patched the few thousand security issues, it broke everything. lol

Just following the instructions, and not getting wise about things, leads to it working very well.

Should be running SARS-CoV-2 samples in no time at all.

Thanks for all the great work guys. You rock
