### ISSUE TITLE
Add --cores argument to snakemake calls

### ISSUE THREAD

**Issue by jameshadfield** [artic-network/rampart#72]
Snakemake >=5.11 made this argument mandatory. Additionally, we should check the snakemake version on startup to ensure it's recent enough to use the features we use in it.

**Comment by sagrudd** [comment]
Is there a timeline for this update? Could this be included for the 1.2.0 release?

**Comment by jameshadfield** [comment]
Should be easy. I'll add this tomorrow and release 1.2.0rc2 for testing

**Comment by jameshadfield** [comment]
Available in 1.2.0rc3 -- if you could test this that'd be wonderful!

```
conda install artic-network/label/test::rampart==1.2.0rc3
```

I plan to release 1.2.0 in ~24 hours if there are no regressions identified

**Comment by sagrudd** [comment]
This all looks great and I have good builds of a container on AMD64 and ARM64v8 using general versions of snakemake from pip = happy camper; thanks!

**Comment by jameshadfield** [comment]
This is part of the v1.2.0 conda release 🎉
