### ISSUE TITLE
ncov2019 protocol version 3

### ISSUE THREAD

**Issue by MaestSi** [artic-network/rampart#81]
Hi,
is it ok to use the protocol named "ARTIC nCoV2019 protocol v1.0", which is provided in the [artic-ncov2019](https://github.com/artic-network/artic-ncov2019/blob/master/rampart/protocol.json) github page, for performing ncov2019 analysis of amplicons sequenced with the protocol version 3?
Thanks,
Simone

**Comment by rambaut** [comment]
Yes. The only difference with respect to how RAMPART operates is that the primers have changed. However the locations of the primers haven't changed except by tiny amounts and these are used in RAMPART just for the visualization of the primer locations.
