### ISSUE TITLE
Inclusion Native Barcoding 96 Expansion barcodes (ONT)

### ISSUE THREAD

**Issue by menickname** [artic-network/rampart#83]
Dear

We have been running the nCoV-2019 protocol for a while and have recently changed to the ONT Native Barcoding 96 Expansion barcodes. However, currently these seem not to be supported when running Rampart as indicated. Are there any plans on a new release of the nCoV-2019 for Rampart or do you have any suggestions how this could be (easily) solved?

Thank you in advance.
Best regards,
Nick Vereecke

**Comment by danieljbridges** [comment]
This would be a great addition. Am guessing it is a matter of updating some configuration files?

**Comment by nickloman** [comment]
We now recommend using MinKNOW in-built demultiplexing (ensure you use the "two barcodes required" option for amplicon work!) and pointing RAMPART to the output folder.

**Comment by Psy-Fer** [comment]
Hey @nickloman , does that mean RAMPART will visualise the 96 samples if done this way? or is it still limited to 24?

If it will show the 96, then that means the change would be on the porechop side, rather than RAMPART itself.

**Comment by nickloman** [comment]
Yes, it will work assuming the barcode directories are created somehow.

**Comment by Psy-Fer** [comment]
Brilliant.

**Comment by rambaut** [comment]
Closing. RAMPART no longer does its own demuxing.
