### ISSUE TITLE
showing different samples

### ISSUE THREAD

**Issue by dinavb** [artic-network/rampart#86]
We run rampart with data from 48 samples, but received only unassigned , without separation to samples. Also it seems only small part of the reads has been analyzed. We run it after the run has finished with already demultiplexed data ( the basecalling and demultiplexing was done on the instrument),
Thank you for advice!

**Comment by jameshadfield** [comment]
Hi @dinavb -- could you paste the "samples" section of the config (if you used one), or the command you ran rampart with & i'll try to take a look.

**Comment by dinavb** [comment]
Thank you, it works now
