### ISSUE TITLE
Latest release: v1.0.6 or v1.2.0?

### ISSUE THREAD

**Issue by sassy-crick** [artic-network/rampart#92]
I am a bit confused about which is actually the latest release? Is that v1.0.6 or v1.2.0? 
Version 1.2.0 is from 1.5.2020 so that should be the latest but the label 'latest' is still on version 1.0.6.
Could you update this or is 1.0.6 the latest production release?
In other words: which one to use for production?

**Comment by rambaut** [comment]
Created 'release' package to tag v1.2.0
